# Generated by Django 4.2.7 on 2023-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(),
        ),
    ]
