# Generated by Django 4.2.7 on 2023-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0005_rename_user_name_faq_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='user',
        ),
        migrations.AddField(
            model_name='faq',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
