# Generated by Django 4.2.7 on 2023-12-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0006_remove_faq_user_faq_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code_check_function', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='tasks_completed',
            field=models.ManyToManyField(blank=True, help_text='Tasks completed by this user.', related_name='completed_by', to='CodeChecker.task', verbose_name='completed tasks'),
        ),
    ]
