# Generated by Django 4.2.7 on 2023-12-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0007_task_customuser_tasks_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tasks_completed',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
