# Generated by Django 4.2.7 on 2023-12-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0008_remove_customuser_tasks_completed_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code_to_check', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, help_text='Tasks completed by this user.', related_name='completed_by_users', to='CodeChecker.task', verbose_name='completed tasks'),
        ),
    ]
