# Generated by Django 4.2.7 on 2023-12-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0009_task_customuser_completed_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='completed_tasks',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
