# Generated by Django 4.2.7 on 2023-12-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0011_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_condition', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/tasks//'),
        ),
        migrations.AddField(
            model_name='task',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CodeChecker.condition'),
        ),
    ]
