# Generated by Django 4.2.6 on 2023-12-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0014_remove_customuser_tasks_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tasks_completed',
        ),
    ]
