# Generated by Django 4.2.6 on 2023-12-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0020_alter_lecture_assignment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_link',
            field=models.URLField(default='http://127.0.0.1:8000/lectures//'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
