# Generated by Django 4.2.7 on 2023-12-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0022_lecture_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='assignment_link',
            field=models.URLField(default='http://127.0.0.1:8000/tasks/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_link',
            field=models.URLField(default='http://127.0.0.1:8000/lectures/'),
        ),
    ]
