# Generated by Django 4.2.7 on 2023-12-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0012_condition_alter_task_link_task_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tasks_completed',
            field=models.ManyToManyField(blank=True, help_text='Tasks completed by this user.', related_name='completed_by', to='CodeChecker.task', verbose_name='completed tasks'),
        ),
    ]
