# Generated by Django 4.2.7 on 2023-12-25 04:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0013_customuser_tasks_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tasks_completed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tasks_completed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
