# Generated by Django 4.2.6 on 2023-12-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0019_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='assignment_link',
            field=models.URLField(default='http://127.0.0.1:8000/tasks//'),
        ),
    ]
