# Generated by Django 4.2.6 on 2023-12-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeChecker', '0021_lecture_lecture_link_lecture_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='info',
            field=models.TextField(default='.'),
        ),
    ]
